### ISSUE TITLE
fslogin?

### ISSUE THREAD

**Issue by rmchurch** [elderamevans/familysearch-python-sdk-opensource#12]
Sorry, this may be because I'm unfamiliar with apache servers. For the oath_desktop_login(), the redirect URL is http://localhost.com:63342/fslogin. What is fslogin? I don't see it anywhere in the project, and my default setup (Mac OS X) doesn't have any fslogin scripts.

**Comment by elderamevans** [comment]
I'm sorry for not being completely clear.
"fslogin" is a fake URL. It can actually be anything of your choosing.

What actually happens is:
You choose your callback URL with FamilySearch Developer Support.
You set that callback URL in the SDK.
It will redirect to `FamilySearch Base`/cis-web/oauth2/v3/authorization?response_type=code&client_id=FOO-BAR
Once you sign in through FamilySearch, it will redirect to `SDK URL and fake directory`?code=-ASDFJKL.
The SDK will grab the access token "code" after the ?code=, and make a request to `FamilySearch Base`/cis-web/oauth2/v3/token, with header of `grant_type=authorization_code&client_id=FOO-BAR&code=-ASDFJKL`
The SDK will then grab the access token.


Thank you for reminding me that I need to include this with the documentation.

**Comment by elderamevans** [comment]
But, yeah, I do need better documentation.
