### ISSUE TITLE
unable to run sample applications

### ISSUE THREAD

**Issue by Jamestra** [elderamevans/familysearch-python-sdk-opensource#13]
When I attempt to run the sample whoami or the web_person on my machine I get the following error:

Traceback (most recent call last):
  File "C:\Users\James\Desktop\FamEarth_Prog\elderamevans-familysearch-python-sdk-opensource-1ffca1d\sample-apps\whoami.py", line 17, in <module>
    from familysearch import FamilySearch
  File "C:\Python34\lib\familysearch\__init__.py", line 215, in <module>
    from . import(discovery_, authentication_, authorities_, changeHistory_,
  File "C:\Python34\lib\familysearch\discovery_.py", line 83, in <module>
    FamilySearch.__bases__ += (Discovery,)
TypeError: Cannot create a consistent method resolution
order (MRO) for bases Discovery, object

Any Ideas on what I need to do to run the sample applications?

**Comment by mikeazo** [comment]
I can confirm this bug in python 2.7.6 on linux.

**Steps to reproduce**
1. Clone the repository from GitHub
2. ```cd familysearch-python-skd-opensource```
3. start python
4. ```>>> from familysearch import FamilySearch```

The output I get is the MRO error. 

I found a [post on StackOverflow](http://stackoverflow.com/questions/10132679/how-do-i-dynamically-add-mixins-as-base-classes-without-getting-mro-errors) that I think may have the solution. If I get the chance, I'll try out some of the ideas there.

**Comment by elderamevans** [comment]
Strange. Let me check this.

**Comment by elderamevans** [comment]
Confirmed. Strange thing is, it's worked fine before...

**Comment by elderamevans** [comment]
So, figured out what I did...

PyLint was chewing me out for (this)[https://github.com/elderamevans/familysearch-python-sdk-opensource/commit/953538a84bfb84d3ca4de75270dd7b5c40c1701c#diff-431c16c5c1c9b13a8c16ca7d741f48c7L67], so I removed it. Adding it back fixed it.

Not sure if it's supposed to be there or not....

**Comment by mikeazo** [comment]
Yeah, putting back in the single line ```class object(object): pass``` and the import works.

**Comment by mikeazo** [comment]
I just tried this and it works:
```
class FSBase(object): pass
class FamilySearch(FSBase):
.
.
.
```

Don't have PyLint setup to see if it complains about something like that. My guess is no.

**Comment by Jamestra** [comment]
I'm not sure I'm following.  I attempted to re-download the file but I got the same error.  I also see I made some additional errors where I did not modify and save the config.ini files.   I have made those changes and passed my dev key that but I still haven't had positive results.  

Just FYI, I'm using windows 8, python 3.4.2 

Thanks for all your help on this

**Comment by elderamevans** [comment]
Well, other than trying to one-line a class, I don't think it'll chew us out otherwise.

**Comment by Jamestra** [comment]
Nice work guys!  I got through

**Comment by Jamestra** [comment]
@elderamevans, I appreciate all your help on this.  I am reaching out for further assistance.  I am working on a spatial studies masters thesis to develop a way of automating genealogic information for processing in a GIS.  to do this I need to implement some complex familysearch api operations but, not being a programmer, I am seriously stymied.  I was hoping I could swap contact information with you so we could collaborate.  If you are interested email me at jamestra@usc.edu and I will share a short powerpoint describing my goals and progress so far.  Thanks again

**Comment by dangerwheeler** [comment]
Was this issue resolved? I dropped the familysearch folder into the sample apps folder and am getting:

Traceback (most recent call last):
  File "whoami.py", line 20, in <module>
    from familysearch import FamilySearch
  File "C:\Users\bryanwh\Downloads\familysearch-python-sdk-opensource-master\fam
ilysearch-python-sdk-opensource-master\sample-apps\familysearch\__init__.py", li
ne 215, in <module>
    from . import(discovery_, authentication_, authorities_, changeHistory_,
  File "C:\Users\bryanwh\Downloads\familysearch-python-sdk-opensource-master\fam
ilysearch-python-sdk-opensource-master\sample-apps\familysearch\discovery_.py",
line 83, in <module>
    FamilySearch.__bases__ += (Discovery,)
TypeError: Cannot create a consistent method resolution
order (MRO) for bases Discovery, object

**Comment by elderamevans** [comment]
Hmm... @mikeazo, I noticed that you had the FSBase class in your fork that you said fixed that... Did that work?

**Comment by mikeazo** [comment]
@elderamevans Yeah, using the FSBase class does fix it. I probably should have created a pull request. If PyLint doesn't like the one like class, you could add a comment on why that class is necessary.

**Comment by elderamevans** [comment]
I can merge right now.

Also, that's where the "disable" arguments comes in handy... <_< >_>
