### ISSUE TITLE
Set up, well, setup.py

### ISSUE THREAD

**Issue by elderamevans** [elderamevans/familysearch-python-sdk-opensource#16]
As it stands right now, there are two ways to "install" the SDK:

1. Keep the `familysearch` folder in with your script.
2. Copy the folder somewhere in your Python installation.

Both are OK, but we can do better than this! Besides, I feel that this should eventually go on PyPI!

The biggest question is: what needs to go where...?

**Comment by dangerwheeler** [comment]
Hey... would definitely use this if I could just pip install this thing.
