### ISSUE TITLE
Instantiating FamilySearch instance makes a lot of remote calls

### ISSUE THREAD

**Issue by dangerwheeler** [elderamevans/familysearch-python-sdk-opensource#18]
When I new up a FamilySearch object, I've noticed that it makes a lot of calls. Can we defer these until we need them?

For example:
https://sandbox.familysearch.org/.well-known/collection
https://sandbox.familysearch.org/platform/collections
https://sandbox.familysearch.org/platform/collections/tree
https://sandbox.familysearch.org/platform/collections/records

**Comment by elderamevans** [comment]
Good point. It's setting up the hypermedia, but that definitely is something to work on.

**Comment by dangerwheeler** [comment]
Cool. 

I'm starting work on a web app, so i'm looking at this through the lens of lots of different users using this simultaneously. This would mean it would be worth rethinking how thread safe this library is. 

If newing up an instance is cheap, I'd probably just create a new instance per request.

**Comment by elderamevans** [comment]
True. I guess my initial thought was to have it "all ready to go", but if it's used on a Web server, with a potential of thousands of logged-in users a day, that's potentially thousands of wasted calls.

**Comment by dangerwheeler** [comment]
Yep. Assuming webservers are using a thread-per-request model, we could consider keeping slowly/rarely/never changing stuff separate (i.e. cache it once in memory) from the state that's likely to change per request (like a given user's access token). 

A couple of options to solve the short term problem:
1. You could have an  init() method that would allow the caller to decide when to make those expense remote calls. 
2. You could lazy load that data the first time a caller needs to use them

Or do both :-).

**Comment by elderamevans** [comment]
I was leaning more towards the 2nd.

We would definitely need the `well-known`/.well-known/collection, as it contains the login endpoints, though...

I'll try to get this "fixed" by the RootsTech Hack-a-Thon...

**Comment by elderamevans** [comment]
OK. I've gotten another Discovery module that trims it to half of its original size, while adding a new function to work on minimizing unnecessary calls, but completely breaks the internals of the SDK that's hypermedia-based.
I'll be adding it to another branch in the meantime.

**Comment by elderamevans** [comment]
Got a temporary solution in place.
