### ISSUE TITLE
Problem using oauth_code_login

### ISSUE THREAD

**Issue by mikeazo** [elderamevans/familysearch-python-sdk-opensource#29]
I'm not sure if I am doing this right, but I wanted to capture the oauth code that I see when using *oauth_desktop_login* and pass it in a later session to *oauth_code_login* so that I don't have to keep logging in.

So what I do is, when I use *oauth_desktop_login*, a browser window pops up, I type in my sandbox username/password. The browser then goes to *http://localhost:63342/fslogin?code=some_code_here*, I copy the code (everything after the =), store it in a variable, then call *oauth_code_login* with that code as the parameter. Unfortunately, this results in a 400 Bad Request error.

Am I doing this right and there is some bug in the *oauth_code_login*? Is there a better way to not have to log in every time before getting the app approved (at which case I can just use *login*)?

**Comment by elderamevans** [comment]
Hmm. I'm a little busy with other things right now, but I'll poke around a bit.

The biggest issue I'm seeing is, as it currently stands, we're making a global variable of the code.
