### ISSUE TITLE
Improper Python code

### ISSUE THREAD

**Issue by dsblank** [elderamevans/familysearch-python-sdk-opensource#38]
The code here:

https://github.com/elderamevans/familysearch-python-sdk-opensource/blob/master/familysearch/__init__.py#L125

is invalid Python: you are calling the constructor method on each of these classes (without an instance of each), but passing in self which is the instance of a FamilySearch object.

If you want to really create instances of each, you should just make them:

```python
        self.discovery = Discovery()
        self.authentication = Authentication()
```
if you need to pass in an instance of FamilySearch, you can do that:
```python
        self.discovery = Discovery(self)
        self.authentication = Authentication(self)
```
but then you need to change the definition of the classes to take a FamilySearch object:

```python
class Discovery:
    def __init__(self, familysearch):
        ....
```
Hope that helps.

**Comment by elderamevans** [comment]
...I suppose this is an instance of "Should not work, but somehow is working"...

What was in before was a "mixin"-type thing, but the way it currently was, code quality checkers were biting my head off for recursive imports.

I'm still trying to find a balance between "recursive imports that code quality checkers won't bite our heads off with" and "have the endpoints available in the main class".

**Comment by dsblank** [comment]
Oh, I see. It is correct, my bad. You could use super to make it more clear. But this is fine. Sorry for the noise.

**Comment by elderamevans** [comment]
Understood. I'm still getting some of the finer details of Python ironed out.

Guess you have a valid point, though.
