### ISSUE TITLE
Proposed syntax

### ISSUE THREAD

**Issue by elderamevans** [elderamevans/familysearch-python-sdk-opensource#9]
While working on the "redirect" function, I realized I needed to have it return a URL. This made me think about the syntax as the rest of the SDK. I realize that, if I were to go through with this, it would take a bit of major tweaking. The good news is, I know of no production app that uses the SDK, so modifying it shouldn't be too drastic of a change, but it's better to do it now than to do it later.

The current syntax:

```Python
fs.get_person(pid)
fs.edit_person(pid, data)
fs.create_person(data)
```

The proposed syntax:

```Python
fs.get(fs.person(pid))
fs.post(fs.person(pid), data)
fs.post(fs.person(), data)
```
I realize that I _could_ have both (for reverse-compatibility and/or preference, but I realize that my choice **now** could affect us 20 years down the road. What say you?

**Comment by mikeazo** [comment]
I like the proposed syntax here and like you say, you could keep the old syntax but add a [deprecation warning](https://docs.python.org/3.4/library/warnings.html)

**Comment by elderamevans** [comment]
Sounds good!

I was basing it off of the Java and Javascript SDKs, which go `FS.GetCurrentUser()` and such.
The main inspiration was the Ruby SDK, which seems to be what the proposed syntax does.

**Comment by elderamevans** [comment]
Went through with it!
